# Dense Retrieval with Higher Recall (Voyage Lite)
description: "Dense retrieval with Voyage Lite, top_k=20 for better recall"

# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration
retrieval:
  type: "dense"
  top_k: 20
  score_threshold: 0.05  # Lower threshold for more results

# Embedding configuration
embedding:
  dense:
    provider: voyage
    model: voyage-3.5-lite
    dimensions: 1024
    api_key_env: VOYAGE_API_KEY
    batch_size: 32
    vector_name: dense
  strategy: dense

# Qdrant collection
qdrant:
  collection: sosum_stackoverflow_hybrid_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Retrievers configuration (required by RetrievalPipelineFactory)
retrievers:
  dense:
    type: dense
    top_k: 20
    score_threshold: 0.05
    performance:
      batch_size: 32
      enable_caching: true
      lazy_initialization: true
    qdrant:
      collection_name: sosum_stackoverflow_hybrid_v1
      vector_name: dense

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10, 20]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 50
experiment_name: "dense_high_recall_voyage_lite"
