# Advanced Hybrid Retrieval Optimization
description: "Advanced hybrid retrieval with optimized fusion parameters"

# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration
retrieval:
  type: "hybrid"
  top_k: 20  # Higher top_k for better recall
  score_threshold: 0.01
  fusion_method: rrf  # Options: 'rrf', 'weighted_sum'
  dense_weight: 0.7   # For weighted_sum method
  sparse_weight: 0.3  # For weighted_sum method

# Embedding configuration
embedding:
  dense:
    provider: google
    model: models/embedding-001
    dimensions: 768
    api_key_env: GOOGLE_API_KEY
    batch_size: 32
    vector_name: dense
  sparse:
    provider: sparse
    model: Qdrant/bm25
    vector_name: sparse
  strategy: hybrid

# Fusion method configuration
fusion:
  method: rrf  # rrf or weighted_sum
  rrf_k: 50    # Smaller k gives more emphasis to top results 
  dense_weight: 0.7  # For weighted_sum
  sparse_weight: 0.3

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10, 15, 20]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 100  # Larger sample size
experiment_name: "hybrid_advanced_rrf"
