# Weighted Sum Hybrid Retrieval Optimization
description: "Hybrid retrieval using weighted sum fusion with optimized weights"

# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration
retrieval:
  type: "hybrid"
  top_k: 20
  score_threshold: 0.01
  fusion_method: weighted_sum
  dense_weight: 0.8  # Emphasize dense retrieval more
  sparse_weight: 0.2

# Embedding configuration
embedding:
  dense:
    provider: google
    model: models/embedding-001
    dimensions: 768
    api_key_env: GOOGLE_API_KEY
    batch_size: 32
    vector_name: dense
  sparse:
    provider: sparse
    model: Qdrant/bm25
    vector_name: sparse
  strategy: hybrid

# Fusion method configuration
fusion:
  method: weighted_sum
  dense_weight: 0.8  # Emphasize dense retrieval more
  sparse_weight: 0.2

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10, 15, 20]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 100
experiment_name: "hybrid_weighted_sum"
