# Hybrid Retrieval Optimization Scenario
description: "Hybrid dense+sparse retrieval for best of both worlds"

# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration
retrieval:
  type: "hybrid"
  top_k: 15
  score_threshold: 0.1

# Embedding configuration
embedding:
  dense:
    provider: google
    model: models/embedding-001
    dimensions: 768
    api_key_env: GOOGLE_API_KEY
    batch_size: 32
    vector_name: dense
  sparse:
    provider: sparse
    model: Qdrant/bm25
    vector_name: sparse
  strategy: hybrid

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10, 15]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 50
experiment_name: "hybrid_dense_sparse"
