# Small Dataset Quick Test
description: "Quick test with Voyage Lite for rapid iteration"

# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration
retrieval:
  type: "dense"
  top_k: 10
  score_threshold: 0.1

# Embedding configuration
embedding:
  dense:
    provider: voyage
    model: voyage-3.5-lite
    dimensions: 1024
    api_key_env: VOYAGE_API_KEY
    batch_size: 32
    vector_name: dense
  strategy: dense

# Qdrant collection
qdrant:
  collection: sosum_stackoverflow_hybrid_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Retrievers configuration (required by RetrievalPipelineFactory)
retrievers:
  dense:
    type: dense
    top_k: 10
    score_threshold: 0.1
    performance:
      batch_size: 32
      enable_caching: true
      lazy_initialization: true
    qdrant:
      collection_name: sosum_stackoverflow_hybrid_v1
      vector_name: dense
    embedding:
      provider: voyage
      model: voyage-3.5-lite
      dimensions: 1024
      api_key_env: VOYAGE_API_KEY
      batch_size: 32

# LLM configuration (optional)
llm:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.0

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 10  # Small for quick testing
experiment_name: "quick_test_voyage_lite"

# Generation configuration (disabled for quick test)
generation:
  enabled: false

# Benchmark configuration (for backwards compatibility)
benchmark:
  evaluation:
    k_values: [1, 5, 10]
    metrics: ["precision", "recall", "f1", "mrr", "ndcg"]
  retrieval:
    strategy: dense
    top_k: 10
    score_threshold: 0.1
