# Sparse Retrieval Optimization Scenario
description: "Sparse retrieval with BM25 for keyword-based search"

# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration
retrieval:
  type: "sparse"
  top_k: 15
  score_threshold: 0.1

# Embedding configuration
embedding:
  sparse:
    provider: sparse
    model: Qdrant/bm25
    batch_size: 32
    vector_name: sparse
  strategy: sparse

# Qdrant collection (using lite collection for sparse-only tests)
qdrant:
  collection: sosum_stackoverflow_hybrid_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Retrievers configuration (required by RetrievalPipelineFactory)
retrievers:
  sparse:
    type: sparse
    top_k: 15
    score_threshold: 0.1
    embedding:
      model: Qdrant/bm25
      provider: sparse
    performance:
      batch_size: 32
      enable_caching: true
      lazy_initialization: true
    qdrant:
      collection_name: sosum_stackoverflow_hybrid_v1
      vector_name: sparse

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10, 15]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 50
experiment_name: "sparse_bm25"
