# DISABLED: Sparse Retrieval Optimization Scenario
# Note: Sparse retriever currently has configuration issues
description: "DISABLED - Sparse retrieval with BM25 (needs fixing)"

# This scenario is disabled because sparse retrieval is not working
disabled: true
disabled_reason: "Sparse retriever has configuration/implementation issues"

# Original configuration (for reference):
# Dataset configuration
dataset:
  path: "/home/spiros/Desktop/Thesis/datasets/sosum/data"
  use_ground_truth: true
  
# Retrieval configuration - DISABLED
retrieval:
  type: "dense"  # Fallback to dense since sparse doesn't work
  top_k: 15
  score_threshold: 0.1

# Embedding configuration
embedding:
  dense:
    provider: google
    model: models/embedding-001
    dimensions: 768
    api_key_env: GOOGLE_API_KEY
    batch_size: 32
    vector_name: dense
  strategy: dense  # Changed from sparse to dense

# Evaluation configuration
evaluation:
  k_values: [1, 5, 10, 15]
  metrics:
    retrieval: ["precision@k", "recall@k", "mrr", "ndcg@k"]

# Experiment parameters
max_queries: 50
experiment_name: "sparse_bm25_disabled"
