# Advanced retrieval pipeline with reranking and filtering
# Production-ready configuration for high-quality results

dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

embedding_strategy: dense

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_minilm_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Advanced Retrieval Pipeline Configuration
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 20  # Get more candidates for reranking
  
  stages:
    - type: score_filter
      config:
        min_score: 0.3  # Filter low-confidence results
    
    - type: reranker
      config:
        model_type: cross_encoder
        model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
        top_k: 10  # Rerank to top 10
    
    - type: duplicate_filter
      config:
        dedup_by: external_id  # Remove duplicates
    
    - type: answer_enhancer  # Enhance with metadata
    
    - type: result_limiter
      config:
        max_results: 5  # Final result count

# Performance settings
fail_on_component_error: false
