# Simple dense retrieval for baseline comparison
dataset:
  name: "stackoverflow_sosum" 
  version: "1.0.0"

embedding_strategy: dense
embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_minilm_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Minimal pipeline for baseline
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 5
    
  stages:
    - type: result_limiter
      config:
        max_results: 5

evaluation:
  metrics: ["recall", "precision"]
  
output_dir: "output/sosum_baseline"
