# Basic dense retrieval pipeline
# Minimal configuration for fast prototyping

dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

embedding_strategy: dense

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_minilm_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Retrieval Pipeline Configuration
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 10
  
  stages: []  # No additional processing stages

# Performance settings
fail_on_component_error: false
