# ============================================================================
# Dense Retrieval - BGE-M3 (With Reranking)
# ============================================================================
# Semantic retrieval with cross-encoder reranking for higher quality
# ============================================================================

# === Embedding Configuration ===
embedding:
  provider: huggingface
  model: BAAI/bge-m3
  dimensions: 1024

# === Qdrant Configuration ===
qdrant:
  host: localhost
  port: 6333
  collection_name: sosum_stackoverflow_bge_splade_recursive_v2
  vector_name: dense

# === Retrieval Pipeline ===
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 10
    score_threshold: 0.0
  
  stages:
    - type: score_filter
      config:
        min_score: 0.3
    
    - type: reranker
      config:
        model_type: cross_encoder
        model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
        top_k: 5
        apply_sigmoid: true
