# Ensemble reranking with multiple models
dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

embedding_strategy: dense
embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_minilm_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Ensemble reranking pipeline
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 15
    
  stages:
    - type: score_filter
      config:
        min_score: 0.25
        
    - type: reranker
      config:
        model_type: ensemble
        rerankers:
          - model_type: cross_encoder
            model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
            weight: 0.6
          - model_type: semantic
            model_name: "sentence-transformers/all-MiniLM-L6-v2"
            weight: 0.4
        aggregation_method: "weighted_average"
        top_k: 7
        
    - type: answer_enhancer
      config:
        enhance_quality: true
        
    - type: result_limiter
      config:
        max_results: 5

evaluation:
  metrics: ["recall", "precision", "mrr", "ndcg"]
  
output_dir: "output/sosum_ensemble"
