# Ensemble Reranking Example
# Combines multiple rerankers with weighted voting

description: "Ensemble reranking with weighted voting"

# Core config at root level
retrieval:
  type: hybrid
  top_k: 40
  fusion:
    method: rrf
    alpha: 0.5
    rrf_k: 60

embedding:
  strategy: hybrid
  dense:
    provider: google
    model: models/embedding-001
  sparse:
    provider: sparse
    model: Qdrant/bm25

qdrant:
  collection_name: sosum_stackoverflow_hybrid_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# ==============================================================================
# ENSEMBLE RERANKING PIPELINE
# ==============================================================================
retrieval_pipeline:
  stages:
    # Ensemble reranker: Combines multiple rerankers with voting
    - type: reranker
      name: ensemble_reranker
      config:
        model_type: ensemble
        rerankers:
          # Reranker 1: CrossEncoder (weight: 0.4)
          - model_type: cross_encoder
            model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
            weight: 0.4
          
          # Reranker 2: BGE (weight: 0.6)
          - model_type: bge
            model_name: BAAI/bge-reranker-base
            weight: 0.6
        
        top_k: 10  # Final ensemble result count
    
    # Additional filtering
    - type: score_filter
      config:
        min_score: 0.3
    
    - type: result_limiter
      config:
        max_results: 5

evaluation:
  k_values: [1, 3, 5, 10]
