# Experimental pipeline for testing new components
# Easy to modify for research and development

dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

embedding_strategy: dense

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_minilm_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Experimental Configuration - Easy to modify
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 15
  
  stages:
    # Experiment with different rerankers
    - type: reranker
      config:
        model_type: bge  # Try BGE instead of CrossEncoder
        model_name: "BAAI/bge-reranker-base"
        top_k: 8
    
    # Experiment with filters
    - type: tag_filter
      config:
        required_tags: ["python"]  # Only Python-related answers
    
    - type: answer_enhancer
    
    # Easy to add/remove components here
    # - type: custom_component
    #   config:
    #     param1: value1

# Performance settings
fail_on_component_error: false
