# Hybrid retrieval with multi-stage reranking
dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

# Base retrieval configuration  
embedding_strategy: hybrid
embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32
  sparse:
    provider: splade
    model_name: "naver/splade-cocondenser-ensembledistil"
    batch_size: 16

qdrant:
  collection: sosum_stackoverflow_hybrid_v1_canary
  dense_vector_name: dense
  sparse_vector_name: sparse

# Advanced retrieval pipeline
retrieval_pipeline:
  # Initial retrieval with more candidates
  retriever:
    type: hybrid
    top_k: 20
    dense_weight: 0.7
    sparse_weight: 0.3
    
  # Multi-stage processing
  stages:
    - type: score_filter
      config:
        min_score: 0.2
        
    - type: duplicate_filter
      config:
        dedup_by: "external_id"
        
    - type: reranker
      config:
        model_type: multistage
        stage1:
          model_type: cross_encoder
          model_name: "cross-encoder/ms-marco-TinyBERT-L-2-v2"
          top_k: 12
        stage2:
          model_type: bge
          model_name: "BAAI/bge-reranker-base"
          top_k: 8
          
    - type: tag_filter
      config:
        required_tags: ["python"]  # Only Python-related answers
        
    - type: answer_enhancer
      config:
        enhance_quality: true
        add_context: true
        compute_readability: true
        
    - type: result_limiter
      config:
        max_results: 5

evaluation:
  metrics: ["recall", "precision", "mrr", "ndcg"]
  
output_dir: "output/sosum_hybrid_advanced"
