# Modern Hybrid Retrieval Configuration for Agent
# Uses the improved hybrid retriever with RRF fusion and CrossEncoder reranking

description: "Advanced hybrid retrieval with dense+sparse fusion and neural reranking"

# Retrieval Pipeline Configuration
retrieval_pipeline:
  retriever:
    type: hybrid
    top_k: 20  # Get more candidates for reranking
    score_threshold: 0.01  # Low threshold for RRF compatibility
    fusion_method: rrf
    
    # Fusion configuration
    fusion:
      method: rrf
      rrf_k: 60  # Standard RRF parameter
      dense_weight: 0.7  # For weighted_sum fallback
      sparse_weight: 0.3
    
    # Embedding configuration
    embedding:
      strategy: hybrid
      dense:
        provider: google
        model: models/embedding-001
        dimensions: 768
        api_key_env: GOOGLE_API_KEY
        batch_size: 32
        vector_name: dense
      sparse:
        provider: sparse
        model: Qdrant/bm25
        vector_name: sparse
    
    # Database configuration
    qdrant:
      collection_name: sosum_stackoverflow_hybrid_v1
      dense_vector_name: dense
      sparse_vector_name: sparse
    
    # Performance settings
    performance:
      lazy_initialization: true
      batch_size: 32
      enable_caching: true
      parallel_search: false

  # Pipeline stages (ordered processing)
  stages:
    - type: retriever
      name: hybrid_retriever
      config:
        retriever_type: hybrid
    
    - type: score_filter
      name: score_filter
      config:
        min_score: 0.01  # Compatible with RRF scores
        max_results: 15
    
    - type: reranker
      name: cross_encoder_reranker
      config:
        model_type: cross_encoder
        model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
        top_k: 10  # Final number of results
        batch_size: 16

# Agent-specific settings
agent:
  max_context_length: 8000
  include_metadata: true
  response_format: detailed
