# Modern Dense Retrieval Configuration for Agent
# Uses the improved dense retriever with neural reranking

description: "Dense semantic retrieval with Google embeddings and neural reranking"

# Retrieval Pipeline Configuration
retrieval_pipeline:
  retriever:
    type: dense
    top_k: 15  # Get candidates for reranking
    score_threshold: 0.0
    
    # Embedding configuration
    embedding:
      provider: google
      model: models/embedding-001
      dimensions: 768
      api_key_env: GOOGLE_API_KEY
      batch_size: 32
      vector_name: dense
    
    # Database configuration
    qdrant:
      collection_name: sosum_stackoverflow_hybrid_v1
      vector_name: dense
    
    # Performance settings
    performance:
      lazy_initialization: true
      batch_size: 32
      enable_caching: true

  # Pipeline stages (ordered processing)
  stages:
    - type: retriever
      name: dense_retriever
      config:
        retriever_type: dense
    
    - type: score_filter
      name: score_filter
      config:
        min_score: 0.0
        max_results: 12
    
    - type: reranker
      name: cross_encoder_reranker
      config:
        model_type: cross_encoder
        model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
        top_k: 10  # Final number of results
        batch_size: 16

# Agent-specific settings
agent:
  max_context_length: 8000
  include_metadata: true
  response_format: detailed
