# Energy Research Papers Configuration
dataset:
  name: "energy_papers"
  version: "1.0.0"
  description: "Energy research papers collection"

# Embedding strategy
embedding_strategy: hybrid

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 16  # Smaller batches for academic content
    device: cuda
    vector_name: dense
  sparse:
    provider: fastembed
    model_name: Qdrant/bm25
    vector_name: sparse

# Chunking configuration
chunking:
  strategy: semantic  # Best for academic papers
  chunk_size: 600     # Larger chunks for academic context
  chunk_overlap: 100
  max_chunk_size: 1000
  sentence_overlap: 2  # More overlap for academic continuity

# Validation settings
validation:
  min_char_length: 100
  max_char_length: 50000  # Allow very long content for papers
  remove_duplicates: true
  clean_html: false  # Academic papers may have minimal HTML
  preserve_code_blocks: false

# Retriever configuration
retriever:
  type: qdrant
  top_k: 10

# Qdrant settings
qdrant:
  collection: energy_papers_hybrid_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Upload settings
upload:
  batch_size: 25  # Smaller batches for large academic content
  wait: true
  versioning: true

# Evaluation settings
evaluation:
  k_values: [1, 3, 5, 10]
  similarity_threshold: 0.75

# Smoke tests
smoke_tests:
  min_success_rate: 0.7  # Lower threshold for specialized domain
  golden_queries:
    - query: "renewable energy optimization"
      min_recall: 0.1
    - query: "solar panel efficiency"
      min_recall: 0.1
    - query: "wind turbine design"
      min_recall: 0.1
    - query: "energy storage systems"
      min_recall: 0.1
    - query: "smart grid technology"
      min_recall: 0.1

# Output configuration
output_dir: "output/energy_papers"

# Embedding cache
embedding_cache:
  enabled: true
  dir: "cache/embeddings/energy_papers"
