# Configuration for Hybrid Dense + Sparse Embeddings
dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

embedding_strategy: hybrid

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32
  sparse:
    provider: sparse
    model_name: Qdrant/bm25
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_hybrid_v1  # Unique collection name
  dense_vector_name: dense
  sparse_vector_name: sparse

output_dir: "output/sosum_hybrid"
embedding_cache:
  dir: "cache/embeddings/sosum_hybrid"

# Processing configuration
chunking:
  chunk_size: 512
  chunk_overlap: 50
  splitter_type: "recursive"

validation:
  max_char_length: 10000
  min_char_length: 10

# Upload configuration
upload:
  batch_size: 50
  wait: true

# Smoke tests
smoke_tests:
  enabled: true
  min_success_rate: 0.7

# Evaluation
evaluation:
  k_values: [1, 3, 5, 10]
  similarity_threshold: 0.8
