# SOSum Stack Overflow Dataset Configuration
# Dataset: https://github.com/BonanKou/SOSum-A-Dataset-of-Extractive-Summaries-of-Stack-Overflow-Posts-and-labeling-tools
dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"
  description: "SOSum: Extractive summaries of Stack Overflow posts (506 questions, 2278 posts)"

# Embedding strategy
embedding_strategy: hybrid

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32
    device: cuda
    vector_name: dense
  sparse:
    provider: fastembed
    model_name: Qdrant/bm25
    vector_name: sparse

# Chunking configuration
chunking:
  strategy: code_aware  # Best for code-heavy content
  chunk_size: 800       # Larger chunks for code context
  chunk_overlap: 100
  preserve_functions: true
  preserve_code_blocks: true

# Validation settings
validation:
  min_char_length: 30       # SOSum has shorter summaries
  max_char_length: 50000    # Allow very long content for complex SO posts
  remove_duplicates: true
  clean_html: true
  preserve_code_blocks: true
  allowed_languages: ["en"]

# Retriever configuration
retriever:
  type: qdrant
  top_k: 15

# Qdrant settings
qdrant:
  collection: sosum_stackoverflow_v1
  dense_vector_name: dense
  sparse_vector_name: sparse

# Upload settings
upload:
  batch_size: 25  # Smaller batches for potentially large posts
  wait: true
  versioning: true

# Evaluation settings
evaluation:
  k_values: [1, 3, 5, 10, 15]
  similarity_threshold: 0.7

# Smoke tests
smoke_tests:
  min_success_rate: 0.8
  golden_queries:
    - query: "Python list comprehension example"
      min_recall: 0.1
    - query: "JavaScript async function"
      min_recall: 0.1
    - query: "How to solve error in code"
      min_recall: 0.1
    - query: "Best practice programming"
      min_recall: 0.1

# Output configuration
output_dir: "output/sosum_stackoverflow"

# Embedding cache
embedding_cache:
  enabled: true
  dir: "cache/embeddings/sosum_stackoverflow"
