# Configuration for Sentence Transformers
dataset:
  name: "stackoverflow_sosum"
  version: "1.0.0"

embedding_strategy: hybrid

embedding:
  dense:
    provider: hf
    model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32

qdrant:
  collection: sosum_stackoverflow_minilm_v1  # Unique collection name
  dense_vector_name: dense
  sparse_vector_name: sparse

output_dir: "output/sosum_minilm"
embedding_cache:
  dir: "cache/embeddings/sosum_minilm"
