# ============================================================================
# MINIMAL CONFIG FOR MAIN.PY - RAG AGENT
# ============================================================================
# This config contains only what's necessary to run the interactive RAG agent.
# For benchmark configs, see benchmark_scenarios/
# ============================================================================

# === LLM Configuration ===
llm:
  model: gpt-4o-mini  # or gpt-4, gpt-3.5-turbo
  temperature: 0.0

# === Agent Retrieval Configuration ===
# Points to the retrieval pipeline config (separate file)
agent_retrieval:
  config_path: pipelines/configs/retrieval/fast_hybrid.yml
