embedding:
  dense:
    batch_size: 32
    model_name: sentence-transformers/all-MiniLM-L6-v2
    provider: hf
    vector_name: dense
  sparse:
    model_name: Qdrant/bm25
    provider: fastembed
    vector_name: sparse
embedding_strategy: hybrid
llm:
  model: gpt-4.1-mini
  provider: openai
  temperature: 0.0
postgres:
  database: tableDB
  host: localhost
  password: admin
  port: 5432
  user: admin
qdrant:
  collection: test_collection_hybrid
  dense_vector_name: dense
  sparse_vector_name: sparse
retrieval:
  config_path: pipelines/configs/retrieval/advanced_reranked.yml
retriever:
  top_k: 10
  type: qdrant
