version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - .:/app
    depends_on:
      - qdrant
    ports:
      - "8000:8000"  # optional, if you add an API later
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]  # Replace with your real entrypoint

volumes:
  qdrant_data:

