dataset:
  name: "stackoverflow_sosum"
  version: "v1.0.0"
  adapter: "stackoverflow"

chunking:
  strategy: "recursive"
  chunk_size: 512
  chunk_overlap: 50
  separators: ["\n\n", "\n", " ", ""]

embedding:
  strategy: "hybrid"
  dense:
    provider: "google"
    model: "models/embedding-001"
    dimensions: 1536        # Available: 128, 256, 512, 768, 1536, 3072 (default: 3072)
    batch_size: 32
  sparse:
    provider: "sparse"
    model: "Qdrant/bm25"
    batch_size: 32

qdrant:
  collection: "sosum_stackoverflow_hybrid_v1"
  dense_vector_name: "dense"
  sparse_vector_name: "sparse"
  distance_metric: "cosine"

upload:
  batch_size: 50
  wait: true
  versioning: true

validation:
  enabled: true
  max_text_length: 10000
  min_text_length: 10

smoke_tests:
  enabled: true
  sample_size: 5
  min_success_rate: 0.7
