# SOSum Stack Overflow Dataset Configuration with BGE Large Embeddings and Code-Aware Chunking
# Dataset: https://github.com/BonanKou/SOSum-A-Dataset-of-Extractive-Summaries-of-Stack-Overflow-Posts-and-labeling-tools
dataset:
  name: "stackoverflow_sosum_bge_code_aware"
  version: "v1.0.0"
  adapter: "stackoverflow"

chunking:
  strategy: "recursive"      # Changed from "recursive" to "code_aware"
  chunk_size: 400            # Larger chunks for 1024-dim embeddings
  chunk_overlap: 100
  separators: ["\n\n", "\n", " ", ""]

embedding:
  strategy: "hybrid"
  dense:
    provider: "hf"   # Changed from "voyage" to "hf"
    model: "BAAI/bge-m3"  # BGE Large model
    dimensions: 384          # BGE Large produces 1024-dim embeddings
    batch_size: 32
  sparse:
    provider: "sparse"
    model: "Qdrant/bm25"
    batch_size: 32

qdrant:
  collection: "sosum_stackoverflow_bge_large_code_aware_v2"
  dense_vector_name: "dense"
  sparse_vector_name: "sparse"

upload:
  batch_size: 50
  wait: true
  versioning: true

validation:
  min_char_length: 10
  max_char_length: 50000
  remove_duplicates: true
  clean_html: true
  preserve_code_blocks: true    # Important for code-aware chunking
  allowed_languages: ["en"]

# Evaluation settings
evaluation:
  k_values: [1, 3, 5, 10, 15]
  similarity_threshold: 0.7

# Smoke tests - code-focused queries for testing
smoke_tests:
  min_success_rate: 0.8
  golden_queries:
    - query: "Python function definition syntax"
      min_recall: 0.1
    - query: "JavaScript async await example"
      min_recall: 0.1
    - query: "How to fix syntax error in code"
      min_recall: 0.1
    - query: "Best practice class inheritance"
      min_recall: 0.1
    - query: "Database connection pooling implementation"
      min_recall: 0.1
    - query: "Exception handling try catch"
      min_recall: 0.1

# Output configuration
output_dir: "output/sosum_stackoverflow_bge_large_code_aware"

# Embedding cache
embedding_cache:
  enabled: true
  dir: "cache/embeddings/sosum_stackoverflow_bge_large_code_aware"