embedding:
  strategy: "hybrid"
  dense:
    provider: "voyage"
    model: "voyage-3.5-lite"
    batch_size: 32
    dimensions: 1024
  sparse:
    provider: "sparse"
    model: "Qdrant/bm25"
    batch_size: 8

qdrant:
  collection: "stackoverflow_voyage_lite"
  host: "localhost"
  port: 6333
  timeout: 300
  distance: "Cosine"
  
chunking:
  method: "recursive"
  chunk_size: 500
  chunk_overlap: 100
  separators: ["\n\n", "\n", " ", ""]

processing:
  validate_documents: true
  enable_duplicate_detection: true
  similarity_threshold: 0.95
  batch_size: 100
  max_retries: 3
  retry_delay: 1.0

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
